# basic options - this is a comment not title
title: Gigi Lin
author: 
email: gigi.lin@mail.utoronto.ca
description: A platform to showcase my many attempts and late-nights for projects which have fascinated me. As John Holt once said "Learning is not the product of teaching. Learning is the product of the activity of learners." 
github_username: ggigigii

# Build settings
markdown: kramdown
theme: minima
