# basic options - this is a comment not title
title: New-awesome-blog
author: ggigigii
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
