# basic options - this is a comment not title
title: Gigi Lin
author: Gigi Lin
email: gigi.lin@mail.utoronto.ca
description: Have more than you show, speak less than you know.
github_username:  ggigigii

# Build settings
markdown: kramdown
theme: minima
